[package]
name = "lyric_charter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
yew = "0.19.3"
js-sys = "0.3.59"
web-sys = { version = "0.3.59", features = ["Blob"]}
gloo = "0.8.0"