[build]
# The index HTML file to drive the bundling process.
target = ".\\lyric_charter_web\\index.html"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = [
    ".\\lyric_charter_web\\src",
    ".\\lyric_charter_lib\\src",
]